#!/bin/bash

function update
{
    REGEX="/shadercache/([0-9]+)"

    if [[ -z $@ ]]; then
        __GAMES_FOLDERS_LIST=$(find /home/$(whoami)/.local/share/Steam/steamapps/shadercache/ -type d -name "DXVK_state_cache")

        for i in $__GAMES_FOLDERS_LIST; do 
            if [[ "$i" =~ $REGEX ]]; then
                APPID=${BASH_REMATCH[1]}
            
                for f in $(ls /home/$(whoami)/.local/share/Steam/steamapps/shadercache/$APPID/DXVK_state_cache/*.dxvk-cache >/dev/null 2>&1); do
                    
                    mv $f{,.bak}
                done

                GAMENAME=$(curl -sX GET https://api.steampowered.com/ISteamApps/GetAppList/v2 | jq -r '.applist.apps | map(select(.appid == '${APPID}')) | map(.name)[0]')

                cp ./"$GAMENAME"/*.dxvk-cache $i
            fi
        done
    else    
        GAMENAME="$@"
        APPID=$(curl -sX GET https://api.steampowered.com/ISteamApps/GetAppList/v2 | jq -r '.applist.apps | map(select(.name == "'"${GAMENAME}"'")) | map(.appid)[0]')

        for f in $(ls /home/$(whoami)/.local/share/Steam/steamapps/shadercache/$APPID/DXVK_state_cache/*.dxvk-cache); do
            mv $f{,.bak}
        done

        cp ./"$GAMENAME"/*.dxvk-cache $i
    fi
}

function restore
{
    GAMENAME="$@"

    APPID=$(curl -sX GET https://api.steampowered.com/ISteamApps/GetAppList/v2 | jq -r '.applist.apps | map(select(.name == "'"${GAMENAME}"'")) | map(.appid)[0]')

    for f in $(ls /home/$(whoami)/.local/share/Steam/steamapps/shadercache/$APPID/DXVK_state_cache/*.bak); do
        rm -f ${f::-4}
        mv $f ${f::-4}
    done
}

eval $1 ${@:2}